<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Queries\GetCurrentUser\" />
      <Folder Include="Queries\GetUserById\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PFinance.Services.Identity.Application\PFinance.Services.Identity.Application.csproj" />
      <ProjectReference Include="..\PFinance.Services.Identity.Common\PFinance.Services.Identity.Common.csproj" />
      <ProjectReference Include="..\PFinance.Services.Identity.Domain\PFinance.Services.Identity.Domain.csproj" />
    </ItemGroup>

</Project>
